name: CI/CD Pipeline for PHP with Semgrep and ZAP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast-scan:
    name: Static Code Analysis (Semgrep)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: 'p/owasp-top-ten'  # You can also use './.semgrep' for custom rules

  build-and-test:
    name: Build and Syntax Check
    runs-on: ubuntu-latest
    needs: sast-scan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, curl

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Run PHP syntax check
      run: |
        find . -name "*.php" -print0 | xargs -0 -n1 php -l

  dast-scan:
    name: Dynamic Scan (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start PHP built-in server
      run: php -S 127.0.0.1:8000 -t public &
    
    - name: Wait for server to start
      run: sleep 5

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.11.0
      with:
        target: 'http://127.0.0.1:8000'
        rules_file_name: '.zap/rules.tsv'  # optional
        fail_action: false
